### ISSUE TITLE
error

### ISSUE THREAD

**Issue by petersang** [RTCat/rtcat_android_v0.2_demo#1]
小米4真机调试

04-30 10:21:15.678 11667-11691/com.shishimao.v2deme E/org.webrtc.Logging: CameraEnumerator: Open camera failed on camera index 0
04-30 10:21:15.678 11667-11691/com.shishimao.v2deme E/org.webrtc.Logging: CameraEnumerator: java.lang.RuntimeException: Fail to connect to camera service
04-30 10:21:15.679 11667-11691/com.shishimao.v2deme E/org.webrtc.Logging: CameraEnumerator: java.lang.RuntimeException: Fail to connect to camera service
                                                                              at android.hardware.Camera.<init>(Camera.java:542)
                                                                              at android.hardware.Camera.open(Camera.java:382)
                                                                              at org.webrtc.CameraEnumerator.enumerateFormats(Unknown Source)
                                                                              at org.webrtc.CameraEnumerator.getSupportedFormats(Unknown Source)
                                                                              at org.webrtc.CameraEnumerationAndroid.getSupportedFormats(Unknown Source)
                                                                              at org.webrtc.VideoCapturerAndroid.getSupportedFormats(Unknown Source)
                                                                              at com.shishimao.sdk.Stream.k(Unknown Source)
                                                                              at com.shishimao.sdk.Stream.g(Unknown Source)
                                                                              at com.shishimao.sdk.au.run(Unknown Source)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at com.shishimao.sdk.tools.LooperExecutor.run(Unknown Source)

**Comment by petersang** [comment]
04-30 10:21:15.682 11667-11691/com.shishimao.v2deme E/RTCatLog: repeat
04-30 10:21:15.684 11667-11691/com.shishimao.v2deme E/AndroidRuntime: FATAL EXCEPTION: Thread-2145
                                                                      Process: com.shishimao.v2deme, PID: 11667
                                                                      java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                          at java.util.Vector.elementAt(Vector.java:326)
                                                                          at java.util.Vector.get(Vector.java:442)
                                                                          at com.shishimao.sdk.Stream.k(Unknown Source)
                                                                          at com.shishimao.sdk.Stream.g(Unknown Source)
                                                                          at com.shishimao.sdk.au.run(Unknown Source)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at com.shishimao.sdk.tools.LooperExecutor.run(Unknown Source)

**Comment by zombiecong** [comment]
Android 系统版本？

**Comment by zombiecong** [comment]
Android6 要自己获得摄像头和麦克风的权限 http://developer.android.com/training/permissions/requesting.html

**Comment by petersang** [comment]
谢谢，果然如此。请问下android 多人聊天可以支撑几人 ？ 几路编解码 ？

**Comment by zombiecong** [comment]
我们没有做人数限制，要看手机的性能了，大部分手机都能支持到2-4人

**Comment by petersang** [comment]
@zombiecong thanks again

**Comment by petersang** [comment]
@zombiecong  大神，我在mac上编译webrtc ios版本， 在gclient sync时 老是出错好像chrominum有些download不了 ， 你有遇到过么

**Comment by zombiecong** [comment]
你挂vpn了吗？
